version: '2'

services:
  web:
    build: .
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: game_platform_web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: game_platform_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: python3 manage.py celery
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
