# Generated by Django 3.2.7 on 2021-09-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Evaluators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(verbose_name='Оценка')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_sum', models.IntegerField(default=0, verbose_name='Сумма всех оценок')),
                ('evaluators', models.ManyToManyField(related_name='User_Evaluators', through='accounts.User_Evaluators', to=settings.AUTH_USER_MODEL, verbose_name='Оценщики')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='user_image/', verbose_name='Фотография')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, verbose_name='Ватсап номер')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, verbose_name='Телеграм номер')),
                ('description', models.TextField(blank=True, verbose_name='О себе')),
                ('steem_account', models.CharField(blank=True, max_length=50, verbose_name='Стим аккаунт')),
                ('dislikes', models.ManyToManyField(related_name='UserProfileDislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(related_name='UserProfileLikes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentOwner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='user_evaluators',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userscores', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('type', models.CharField(choices=[('1', 'Коментарий'), ('2', 'Сражение создано'), ('3', 'Сражение завершенно'), ('4', 'Сражение началось'), ('5', 'Баланс пополнен'), ('6', 'Сражение отменено'), ('7', 'Предложение на сражение')], max_length=50, verbose_name='Тип')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='notifications/', verbose_name='Изображение')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомления',
                'verbose_name_plural': 'Уведомлении',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_number', models.IntegerField(verbose_name='Номер пасспорта')),
                ('tin', models.IntegerField(verbose_name='ИНН')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=15, verbose_name='Страна')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('address', models.CharField(max_length=40, verbose_name='Адресс')),
                ('passport_image', models.ImageField(upload_to='user_passport_image', verbose_name='Фото пасспорта')),
                ('address_confirming', models.ImageField(upload_to='user_address_confirming', verbose_name='Документ подтверждаюший адресс проживания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Идентификация',
                'verbose_name_plural': 'Идентификация',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user_evaluators',
            unique_together={('evaluator', 'user')},
        ),
    ]
