# Generated by Django 3.2.7 on 2021-09-10 11:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='notifications/', verbose_name='Изображение'),
        ),
    ]
