# Generated by Django 3.2.7 on 2021-09-14 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_battle_start_date'),
        ('accounts', '0004_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-09-14 11:09:24.360708', verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_evaluators',
            name='score',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='UserProfileDislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='UserProfileLikes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='User_Evaluators', through='accounts.User_Evaluators', to=settings.AUTH_USER_MODEL, verbose_name='Оценщики'),
        ),
        migrations.CreateModel(
            name='BattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('1', 'Поражение'), ('2', 'Победа'), ('3', 'Ничя')], max_length=100, verbose_name='Результат')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.battle', verbose_name='Сражение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Истоия сражений',
                'verbose_name_plural': 'Истории сражений',
            },
        ),
    ]
