# Generated by Django 3.2.7 on 2021-09-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210914_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adequacy_rate_sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма рейтинга адекватности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courtesy_rate_sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма рейтинга вежливости'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='punctuality_rate_sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма рейтинга пунктуальности'),
        ),
        migrations.AddField(
            model_name='userscores',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Оценщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscores',
            name='score',
            field=models.SmallIntegerField(default=1, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscores',
            name='type',
            field=models.CharField(choices=[('1', 'Вежливость'), ('2', 'Пунктуальность'), ('3', 'Адекватность')], default=1, max_length=50, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'Коментарий'), ('2', 'Сражение создано'), ('3', 'Сражение завершенно'), ('4', 'Сражение началось'), ('5', 'Баланс пополнен'), ('6', 'Сражение отменено'), ('7', 'Предложение на сражение'), ('8', 'Успешно выведено')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='userscores',
            unique_together={('evaluator', 'user', 'type')},
        ),
        migrations.RemoveField(
            model_name='userscores',
            name='evaluators',
        ),
        migrations.RemoveField(
            model_name='userscores',
            name='score_sum',
        ),
        migrations.DeleteModel(
            name='User_Evaluators',
        ),
    ]
