# Generated by Django 3.2.7 on 2021-09-10 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='border_image',
            field=models.ImageField(default=1, upload_to='gameimages/f{name}', verbose_name='Картинка игры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(default=1, upload_to='gameicons/f{name}', verbose_name='Иконка игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='reposts',
            field=models.ManyToManyField(blank=True, related_name='reposts', to=settings.AUTH_USER_MODEL, verbose_name='Репосты'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 6, 25, 1, 12858, tzinfo=utc), verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='battle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.battle', verbose_name='Битва'),
        ),
        migrations.AlterField(
            model_name='game',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подпсчики'),
        ),
    ]
