# Generated by Django 3.2.7 on 2021-09-10 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210910_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battleresponse',
            options={'ordering': ['-id'], 'verbose_name': 'Предложение на битву', 'verbose_name_plural': 'Предложения на битву'},
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 7, 41, 27, 263628, tzinfo=utc), verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_member_player_2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_member_player_3', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 3'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_member_player_4', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 4'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_member_player_5', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 5'),
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_response_player_2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2'),
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_response_player_3', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 3'),
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_response_player_4', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 4'),
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_response_player_5', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 5'),
        ),
    ]
