# Generated by Django 3.2.7 on 2021-09-10 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210910_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 9, 36, 28, 375657, tzinfo=utc), verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='game',
            name='border_image',
            field=models.ImageField(upload_to='gameimages', verbose_name='Картинка игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(upload_to='gameicons', verbose_name='Иконка игры'),
        ),
    ]
