# Generated by Django 3.2.7 on 2021-09-10 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210910_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 11, 2, 2, 299381, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
