# Generated by Django 3.2.7 on 2021-09-10 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_battle_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 11, 47, 52, 977635, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
