# Generated by Django 3.2.7 on 2021-09-14 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_battle_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 5, 3, 51, 896232, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
