# Generated by Django 3.2.7 on 2021-09-14 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_battle_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 6, 48, 54, 420427, tzinfo=utc), verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('1', 'В ожидании'), ('2', 'В процессе'), ('3', 'Закончено'), ('4', 'Отменён')], max_length=50, verbose_name='Статус'),
        ),
    ]
