# Generated by Django 3.2.7 on 2021-09-16 07:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20210914_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='is_published',
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Battle_battle_response', to='main.battleresponse', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.CharField(blank=True, choices=[('1', 'Заказчик'), ('2', 'Исполнитель')], max_length=50, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 6, 59, 53, 622762, tzinfo=utc), verbose_name='Время начало'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('1', 'В ожидании'), ('2', 'В процессе'), ('3', 'Закончено'), ('4', 'Отменён')], default='1', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='accounts.user', verbose_name='Игрок 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_2',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_3',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_4',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlemembers',
            name='player_5',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='accounts.user', verbose_name='Игрок 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_2',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_3',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_4',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleresponse',
            name='player_5',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='Игрок 5'),
            preserve_default=False,
        ),
    ]
