# Generated by Django 3.2.7 on 2021-09-16 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210916_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 9, 38, 206171, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
