# Generated by Django 3.2.7 on 2021-09-20 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210916_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 15, 16, 271129, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
