# Generated by Django 3.2.7 on 2021-09-21 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_battle_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 6, 38, 58, 979845, tzinfo=utc), verbose_name='Время начало'),
        ),
    ]
